### ISSUE TITLE
where can I set the value of lambda in eq.(2) and (3)?

### ISSUE THREAD

**Issue by rguo12** [Lee-Gihun/MixCo-Mixup-Contrast#2]
It seems I could not find it in https://github.com/Lee-Gihun/MixCo-Mixup-Contrast/blob/main/moco/utils/loss_fn.py

Thanks for any guidance.

**Comment by sungnyun** [comment]
Hi. Thank you for your interest.
In the [encoder](https://github.com/Lee-Gihun/MixCo-Mixup-Contrast/blob/main/moco/models/encoder.py),
you will find the 'img_mixer' function.
There is lambda for mixing images and labels.
