### ISSUE TITLE
question about the pre-trained models

### ISSUE THREAD

**Issue by lichen14** [Lee-Gihun/MixCo-Mixup-Contrast#3]
Thanks for sharing the code of MixCo, which helped us a lot.

As you mentioned in the paper, "ResNet-34 and ResNet-50 encoder are trained for 200 epochs with batch size 128, and ResNet-18 is trained with 100 epochs​", I am writing to ask if you can share the pre-trained models?​ Especially the counterparts in appendix​ C.2.
![image](https://user-images.githubusercontent.com/25859465/146709316-38f707d5-3e25-4e49-be19-8676d95b9f9a.png)

Thanks for your work and we will cite this paper in our future work.

**Comment by sungnyun** [comment]
You can download the resnet18 file in this [link](https://drive.google.com/file/d/1Dg_SNGBmpyPCRIvrt8EIfQrUEIvtWasW/view?usp=sharing).
